image: ruby:latest

before_script:
  - ruby -v
  - gem install bundler
  - bin/setup

rubocop:
  script:
  - bundle exec rubocop

rspec:
  script:
  - bundle exec rspec
  artifacts:
    paths:
      - web/coverage/

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -s web -d public
  artifacts:
    paths:
    - public
  only:
  - master
